apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: edge-crd
spec:
  releaseName: edge-crd
  chart:
    spec:
      chart: edge-kubernetes-crd
      sourceRef:
        kind: HelmRepository
        name: microsoft-iotedge
        namespace: flux-system
      version: "0.2.11"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3

