apiVersion: v1
kind: Service
metadata:
  name: fake-data
  namespace: kafka-streams
  labels:
    app: fake-data
spec:
  type: ClusterIP
  selector:
    app: fake-data
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
