apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: edge1-secrets
  namespace: iotedge
spec:
  encryptedData:
    device-connection-string: AgDPHS8I8ANmbT/3UKINihXjyKwW2ietXLURN5ZQ+qmHEmZaBsP5nHmxJjToha8N4zk64PKKceoSa808prKvq/lEpofmOWUigvR6womo9VEki6HwvlFjRzNsMf0bpOonsfFWuMURwBdpWp906bSj0Z0U083LQ7Ol+ZyMvWtZM0vsAjfKcTGLSJt04a67UWun1raKvu/cZg2+960+ysU9oPaA3QVg2tewIBW7Y32LeIyjo/0Adf6eVIMlhD7Fr2zwlDf3h+BZ22uO4esTyjO0RMOkgW9ZpQruqyjns1vNzaFGKRqviCZU8I1KX8rTN/9RcvFQGb5NXr1OGuuBuuP1Xu6QYaSzJNVXfz/ta/vj9Arv2FFabVZxYqxTbU95AKxjKP+1s1gPrnUCf1fS2+BPbrEPY/Ro6G8jKjCs/de/ZQX2M9EaVn6VfGY54VUrtM1KAbJxwwaPE6yncyFagJNod4vDnsuUYleQDSCQ8jAzG/Pq5MjphSTzEHQlJLYoseGwW7eeNu3KT/iIpMcxNvrrUIH6LHRWcaebTaM0trHRHlmGx9YArf5WBrL+7pR3nww2x9o6HYNa55E7iCRGM8qP5Aa91456Tk5BJnA2ANYwpyuq8debGcDvCDMixhcAf/k5py3FOKs/jzOI1QNnxG+wVsCm4rQvKSX8jcQV3q1NtaBrN516UlAzbBIKYnK3Hql8s3Bu+XKp+/L4RgJ/TQwuEAfp64T4avD/iSulkGp7eHLxVFKdJg==
  template:
    metadata:
      name: edge1-secrets
      namespace: iotedge