apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
spec:
  releaseName: strimzi
  chart:
    spec:
      chart: strimzi-kafka-operator
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      version: "0.21.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    logLevel: ERROR
